# Generated by Django 4.1.9 on 2024-06-14 15:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project", "0011_alter_projectmembership_user"),
        ("user_profile", "0006_profile_node"),
        ("storage", "0006_alter_file_import_folder_alter_file_path"),
        ("challenge", "0006_alter_challenge_origin"),
        ("study_management", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("celery_task_id", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FAILURE", "Failure"),
                            ("PENDING", "Pending"),
                            ("STARTED", "Started"),
                            ("SUCCESS", "Success"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("progress", models.FloatField(default=0.0)),
                ("export_folder", models.CharField(max_length=1000)),
                (
                    "challenge",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="challenge.challenge"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to="user_profile.profile",
                    ),
                ),
                ("files", models.ManyToManyField(blank=True, to="storage.file")),
                (
                    "project",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="project.project"),
                ),
                (
                    "study",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="study_management.study"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
