# Generated by Django 4.1.9 on 2024-06-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage_exporter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportjob",
            name="celery_task_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="exportjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("FAILURE", "Failure"),
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("SUCCESS", "Success"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
