# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_profile", "0001_initial"),
        ("storage", "0002_initial"),
        ("file_transfer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_by",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="transferitem",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="transfers", to="storage.file"
            ),
        ),
        migrations.AddField(
            model_name="transferitem",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="transfers", to="user_profile.profile"
            ),
        ),
    ]
