# Generated by Django 4.1.9 on 2023-11-09 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_transfer", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferitem",
            name="source",
        ),
    ]
