# Generated by Django 4.1.9 on 2023-11-09 12:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_projectmembership_status"),
        ("file_transfer", "0003_remove_transferitem_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferJob",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("query", models.JSONField(blank=True, default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transfer_jobs", to="project.project"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="transferitem",
            name="transfer_job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_items",
                to="file_transfer.transferjob",
            ),
            preserve_default=False,
        ),
    ]
