# Generated by Django 4.1.9 on 2024-03-04 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0006_profile_node"),
        ("file_transfer", "0004_transferjob_transferitem_transfer_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferjob",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_by",
                to="user_profile.profile",
            ),
        ),
    ]
