# Generated by Django 4.1.9 on 2024-06-05 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0011_alter_projectmembership_user"),
        ("file_transfer", "0005_transferjob_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferjob",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_jobs",
                to="project.project",
            ),
        ),
    ]
