# Generated by Django 4.1.9 on 2024-06-14 16:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0006_alter_file_import_folder_alter_file_path"),
        ("user_profile", "0006_profile_node"),
        ("file_transfer", "0006_alter_transferjob_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadToken",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("token", models.CharField(max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to="user_profile.profile",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="download_tokens", to="storage.file"
                    ),
                ),
                (
                    "for_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_tokens",
                        to="user_profile.profile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="downloadtoken",
            constraint=models.UniqueConstraint(fields=("file", "token"), name="unique_file_token"),
        ),
        migrations.AddConstraint(
            model_name="downloadtoken",
            constraint=models.Index(fields=["token"], name="token_idx"),
        ),
    ]
