# Generated by Django 4.1.9 on 2024-06-18 09:17

import apps.federation.file_transfer.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_transfer", "0007_downloadtoken_downloadtoken_unique_file_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadtoken",
            name="token",
            field=models.CharField(default=apps.federation.file_transfer.models.generate_token, max_length=50),
        ),
    ]
