# Generated by Django 4.1.9 on 2024-10-10 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0006_alter_challenge_origin"),
        ("file_transfer", "0008_alter_downloadtoken_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadtoken",
            name="challenge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="download_tokens",
                to="challenge.challenge",
            ),
        ),
    ]
