# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("study_management", "0001_initial"),
        ("storage", "0002_initial"),
        ("core", "0001_initial"),
        ("terminology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyarm",
            name="codes",
            field=models.ManyToManyField(blank=True, related_name="%(class)s_codes", to="terminology.code"),
        ),
        migrations.AddField(
            model_name="studyarm",
            name="files",
            field=models.ManyToManyField(blank=True, related_name="study_arms", to="storage.file"),
        ),
        migrations.AddField(
            model_name="studyarm",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="arms", to="study_management.study"
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="annotations",
            field=models.ManyToManyField(blank=True, related_name="%(class)s_annotations", to="core.annotation"),
        ),
        migrations.AddField(
            model_name="study",
            name="codes",
            field=models.ManyToManyField(blank=True, related_name="%(class)s_codes", to="terminology.code"),
        ),
    ]
