# Generated by Django 4.1.9 on 2025-02-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extra_data", "0004_alter_extradata_origin"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="extradata",
            constraint=models.Index(fields=["file"], name="idx_file"),
        ),
    ]
