# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComputingJobResult",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("identifier", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ComputingJobArtifact",
            fields=[
                (
                    "computingjobresult_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="computing_artifact.computingjobresult",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("computing_artifact.computingjobresult",),
        ),
    ]
