# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("node", "0001_initial"),
        ("computing_artifact", "0001_initial"),
        ("computing_executions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="computingjobresult",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origin",
                to="node.node",
            ),
        ),
        migrations.AddField(
            model_name="computingjobartifact",
            name="computing_job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="computing_executions.computingjobexecution",
            ),
        ),
    ]
