# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("storage", "0001_initial"),
        ("computing_artifact", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="computingjobartifact",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="computing_job_artifacts", to="storage.file"
            ),
        ),
    ]
