# Generated by Django 4.1.9 on 2023-10-31 13:58

import apps.share.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("study_management", "0001_initial"),
        ("fileset", "0001_initial"),
        ("terminology", "0001_initial"),
        ("computing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TileSet",
            fields=[
                (
                    "fileset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="fileset.fileset",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("importing", "Importing"),
                            ("copying", "Copying"),
                            ("locked", "Locked"),
                        ],
                        default="idle",
                        max_length=10,
                    ),
                ),
                ("tiling_params", models.JSONField(blank=True, default=dict)),
                (
                    "computing_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filesets",
                        to="computing.computingjobdefinition",
                    ),
                ),
                (
                    "included_files",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tilesets",
                        to="fileset.fileset",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="copies",
                        to="tile_management.tileset",
                    ),
                ),
                (
                    "study_arm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tilesets",
                        to="study_management.studyarm",
                    ),
                ),
                ("terms", models.ManyToManyField(blank=True, related_name="tilesets", to="terminology.code")),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.share.models.ShareableMixin, "fileset.fileset"),
        ),
    ]
