# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComputingJobExecution",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("identifier", models.CharField(blank=True, max_length=500, null=True)),
                ("executed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("pending", "Pending"),
                            ("error", "Error"),
                            ("success", "Success"),
                            ("created", "Created"),
                            ("creating", "Creating"),
                            ("preparing", "Preparing"),
                            ("failed", "Failed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("acceptance_pending", "Acceptance Pending"),
                            ("killed", "Killed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("finished_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("k8s_data", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default=None, null=True)),
                ("batch_number", models.IntegerField(default=-1)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
