# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_profile", "0001_initial"),
        ("storage", "0002_initial"),
        ("computing_executions", "0001_initial"),
        ("computing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="computingjobexecution",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_by",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="computingjobexecution",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="computing.computingjobdefinition",
            ),
        ),
        migrations.AddField(
            model_name="computingjobexecution",
            name="executed_before",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executed_after",
                to="computing_executions.computingjobexecution",
            ),
        ),
        migrations.AddField(
            model_name="computingjobexecution",
            name="input",
            field=models.ManyToManyField(blank=True, to="storage.file"),
        ),
    ]
