# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("challenge_submission", "0001_initial"),
        ("challenge_leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardentry",
            name="metrics",
            field=models.ManyToManyField(related_name="metric_values", to="challenge_submission.targetmetricvalue"),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaderboard_entry",
                to="challenge_submission.submission",
            ),
        ),
    ]
