# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_profile", "0001_initial"),
        ("auth_certificate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="issued_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates_issued",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="issued_for",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="certificates", to="user_profile.profile"
            ),
        ),
        migrations.AddConstraint(
            model_name="certificate",
            constraint=models.UniqueConstraint(fields=("issued_by", "issued_for"), name="unique_issued_by_issued_for"),
        ),
    ]
