# Generated by Django 4.1.9 on 2023-11-17 11:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project", "0005_alter_projectmembership_status"),
        ("node", "0004_node_common_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("project_create", "Project Create"),
                            ("project_invite", "Project Invite"),
                            ("project_invite_accept", "Project Invite Accepted"),
                            ("project_invite_decline", "Project Invite Declined"),
                            ("receive_share", "Receive Share"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "context_project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_contexts",
                        to="project.project",
                    ),
                ),
                (
                    "object_project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_objects",
                        to="project.project",
                    ),
                ),
                ("subject", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="node.node")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
