# Generated by Django 4.1.9 on 2023-11-17 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0004_node_common_name"),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="object_node",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="event_objects", to="node.node"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="verb",
            field=models.CharField(
                choices=[
                    ("project_create", "Project Create"),
                    ("project_invite", "Project Member Invite"),
                    ("project_invite_accept", "Project Member Invite Accepted"),
                    ("project_invite_decline", "Project Member Invite Declined"),
                    ("project_member_removed", "Project Member Removed"),
                    ("receive_share", "Receive Share"),
                ],
                max_length=200,
            ),
        ),
    ]
