# Generated by Django 4.1.9 on 2023-11-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_event_object_node_alter_event_verb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="verb",
            field=models.CharField(
                choices=[
                    ("project_create", "Project Create"),
                    ("project_invite", "Project Member Invite"),
                    ("project_invite_accept", "Project Member Invite Accepted"),
                    ("project_invite_decline", "Project Member Invite Declined"),
                    ("project_member_removed", "Project Member Removed"),
                    ("share_receive", "Share Receive"),
                ],
                max_length=200,
            ),
        ),
    ]
