# Generated by Django 4.1.9 on 2024-02-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0006_profile_node"),
        ("event", "0003_alter_event_verb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="subject",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="user_profile.profile"),
        ),
    ]
