# Generated by Django 4.1.9 on 2024-02-23 14:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_profile", "0005_profile_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="FederationInvitation",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("accepted", "Accepted"), ("decline", "Decline"), ("open", "Open")],
                        default="open",
                        max_length=8,
                    ),
                ),
                ("from_name", models.CharField(max_length=100)),
                ("from_identifier", models.CharField(max_length=100)),
                ("from_organization", models.CharField(max_length=100)),
                ("from_certificate_thumbprint", models.CharField(max_length=1000)),
                (
                    "to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="federation_invitations",
                        to="user_profile.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
