# Generated by Django 4.1.9 on 2024-02-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federation_invitation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="federationinvitation",
            name="remote_invite_id",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
