# Generated by Django 4.1.9 on 2024-02-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federation_invitation", "0002_federationinvitation_remote_invite_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="federationinvitation",
            name="from_certificate_thumbprint",
        ),
        migrations.AddField(
            model_name="federationinvitation",
            name="node_data",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
