# Generated by Django 4.1.9 on 2024-02-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federation_invitation", "0003_remove_federationinvitation_from_certificate_thumbprint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federationinvitation",
            name="from_organization",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="federationinvitation",
            name="remote_invite_id",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
