# Generated by Django 4.1.9 on 2024-02-27 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_alter_projectmembership_status"),
        ("federation_invitation", "0004_alter_federationinvitation_from_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="federationinvitation",
            name="project",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="project.project",
            ),
        ),
    ]
