# Generated by Django 4.1.9 on 2024-02-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federation_invitation", "0005_federationinvitation_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="federationinvitation",
            name="project_data",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
