# Generated by Django 4.1.9 on 2024-03-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federation_invitation", "0006_federationinvitation_project_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federationinvitation",
            name="status",
            field=models.CharField(
                choices=[("accepted", "Accepted"), ("declined", "Declined"), ("open", "Open")],
                default="open",
                max_length=8,
            ),
        ),
    ]
