# Generated by Django 4.1.9 on 2024-09-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0011_alter_profile_communication_allowed_with_users"),
        ("federation_invitation", "0007_alter_federationinvitation_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="federationinvitation",
            name="from_identifier",
        ),
        migrations.RemoveField(
            model_name="federationinvitation",
            name="from_name",
        ),
        migrations.RemoveField(
            model_name="federationinvitation",
            name="from_organization",
        ),
        migrations.RemoveField(
            model_name="federationinvitation",
            name="node_data",
        ),
        migrations.RemoveField(
            model_name="federationinvitation",
            name="remote_invite_id",
        ),
        migrations.AddField(
            model_name="federationinvitation",
            name="from_user",
            field=models.ForeignKey(
                default="6bbfed92-a2f9-420d-9cab-d913c72682f8",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="federation_invitations_sent",
                to="user_profile.profile",
            ),
            preserve_default=False,
        ),
    ]
