# Generated by Django 4.1.9 on 2025-11-10 13:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("challenge", "0006_alter_challenge_origin"),
        ("user_profile", "0013_profile_eth_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeWebsite",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("identifier", models.CharField(blank=True, max_length=500, null=True)),
                ("slogan", models.TextField(blank=True, null=True)),
                ("hero", models.TextField(blank=True, null=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("affiliation", models.TextField(blank=True, null=True)),
                (
                    "challenge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="website", to="challenge.challenge"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to="user_profile.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
