# Generated by Django 4.1.9 on 2025-11-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenge_website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengewebsite",
            name="selected_endpoints",
            field=models.JSONField(
                blank=True, default=list, help_text="List of selected endpoint names to display on the website"
            ),
        ),
    ]
