# Generated by Django 4.1.9 on 2025-11-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenge_website", "0002_add_selected_endpoints"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengewebsite",
            name="bibtex",
            field=models.TextField(blank=True, help_text="BibTeX citation for the challenge/dataset", null=True),
        ),
        migrations.AddField(
            model_name="challengewebsite",
            name="citation",
            field=models.TextField(blank=True, help_text="Citation text for the challenge/dataset", null=True),
        ),
    ]
