from django.urls import path, include
from rest_framework.routers import SimpleRouter

from apps.project import datatables, views

router = SimpleRouter()
router.register(r'datatable-file', viewset=datatables.FileTableView, basename='datatable-file')

urlpatterns = [
                  path('', view=views.ListView.as_view(), name='list'),
                  path('<uuid:pk>/', view=views.DetailView.as_view(), name='detail'),
                  path('<uuid:pk>/ground_truth/', include('apps.project.project_ground_truth.urls'),
                       name='ground_truth'),
                  path('<uuid:pk>/my_data_ground_truth/', views.SetGroundTruthOfMyData.as_view(),
                       name='my_data_ground_truth'),
                  path('<uuid:pk>/my_data_ground_truth/action/', views.SetGroundTruthOfMyDataAction.as_view(),
                       name='my_data_ground_truth_action'),
                  path('create/', view=views.CreateProjectView.as_view(), name='create'),
                  path('<uuid:pk>/events/', view=views.EventListView.as_view(), name='events'),
                  path('<uuid:pk>/dashboard/', view=views.DashboardView.as_view(), name='dashboard'),
                  path('<uuid:pk>/<uuid:view_pk>/', view=views.ViewView.as_view(), name='detail-view'),
                  path('<uuid:pk>/transfers/<uuid:job_pk>/', view=views.TransferJobDetailView.as_view(),
                       name='transfer-job'),
                  path('<uuid:pk>/transfers/<uuid:job_pk>/action/', view=views.TransferJobDetailActionView.as_view(),
                       name='transfer-job-action'),
                  path('<uuid:pk>/transfers/', view=views.TransferJobListView.as_view(), name='transfer-job-list'),
                  path('<uuid:pk>/download/', view=views.DownloadFilesView.as_view(), name='download'),
                  path('<uuid:pk>/download-query/', view=views.DownloadFilesActionView.as_view(),
                       name='download-query'),
                  # path('<uuid:pk>/create-share/', view=views.CreateShareView.as_view(), name='create-share'),
                  path('<uuid:pk>/share/query/', view=views.CreateShareQueryView.as_view(), name='create-share-query'),
                  path('<uuid:pk>/shares/query/filter/',
                       view=views.CreateShareActionQueryFilterView.as_view(), name='create-share-query-filter'),
                  # path('<uuid:pk>/shares/upload/',
                  #      view=views.CreateShareActionQueryFilterView.as_view(), name='create-share-query-filter'),

                  path('<uuid:pk>/share/query/action/', view=views.CreateShareQueryActionView.as_view(),
                       name='create-share-query-action'),
                  path('<uuid:pk>/share/action/', view=views.CreateShareActionView.as_view(),
                       name='create-share-action'),
                  path('<uuid:pk>/shares/', view=views.ShareListView.as_view(), name='share-list'),
                  path('<uuid:pk>/shares/<uuid:share_pk>/', view=views.ShareDetailView.as_view(), name='share-detail'),
                  path('<uuid:pk>/shares/<uuid:share_pk>/action/', view=views.ShareDetailActionView.as_view(),
                       name='share-detail-action'),
                  path('case/', include(('apps.project.project_case.urls', 'project_case'))),
                  path('<uuid:pk>/import/', include(('apps.project.import_data.urls', 'import_data'))),
                  path('shared-with-me/', views.DataSharedWithMeView.as_view(), name='data-shared-with-me'),
                  path('<uuid:pk>/terminology/', view=views.TerminologyListView.as_view(), name='terminology'),
                  path('<uuid:pk>/terminology/add/', view=views.TerminologyAddDialog.as_view(),
                       name='terminology-dialog-add'),
                  path('<uuid:pk>/terminology/action/', view=views.TerminologyDeleteAction.as_view(),
                       name='terminology-action'),
                  path('<uuid:pk>/send-to-annotater/', view=views.SendFilesToAnnotatorView.as_view(),
                       name='send-to-annotater'),
                  path('<uuid:pk>/export/', view=views.ExportAsCSVView.as_view(),
                       name='export'),
                  path('<uuid:pk>/collaborators/', view=views.CollaboratorListView.as_view(), name='collaborator-list'),
                  path('<uuid:pk>/submissions/', view=views.PartSubmissionListView.as_view(), name='submissions'),
                  path('<uuid:pk>/collaborators/delete/', view=views.DeleteCollaboratorActionView.as_view(),
                       name="collaborator-delete"),
                  path('invites/', view=views.InvitesView.as_view(), name='invites'),

                  path('<uuid:pk>/website/', include('apps.project.website.urls'),
                       name='website'),
              ] + router.urls
