# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InboxMessage",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("message", models.JSONField(default=dict)),
                ("via", models.CharField(max_length=500)),
                ("destination", models.CharField(max_length=200)),
                (
                    "box",
                    models.CharField(
                        choices=[("inbox", "Inbox"), ("outbox", "Outbox")],
                        default="inbox",
                        editable=False,
                        max_length=10,
                    ),
                ),
                ("processed", models.BooleanField(default=False)),
                ("processing", models.BooleanField(default=False)),
                ("tries", models.IntegerField(default=0)),
                ("status_code", models.IntegerField(blank=True, default=None, null=True)),
                ("error", models.TextField(blank=True, default=None, null=True)),
                ("hash", models.CharField(max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
