# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_profile", "0001_initial"),
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxmessage",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_received_messages",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="inboxmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_sent_messages",
                to="user_profile.profile",
            ),
        ),
    ]
