# Generated by Django 4.1.9 on 2023-11-01 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0002_initial"),
        ("inbox", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxmessage",
            name="extra_data",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="inboxmessage",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_received_messages", to="node.node"
            ),
        ),
        migrations.AlterField(
            model_name="inboxmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_sent_messages", to="node.node"
            ),
        ),
    ]
