# Generated by Django 4.1.9 on 2023-11-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0004_inboxmessage_response_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxmessage",
            name="business_key",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
