# Generated by Django 4.1.9 on 2024-02-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0006_profile_node"),
        ("inbox", "0005_inboxmessage_business_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboxmessage",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_received_messages",
                to="user_profile.profile",
            ),
        ),
        migrations.AlterField(
            model_name="inboxmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_sent_messages",
                to="user_profile.profile",
            ),
        ),
    ]
