# Generated by Django 4.1.9 on 2024-02-27 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0006_alter_inboxmessage_recipient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inboxmessage",
            name="via",
        ),
    ]
