# Generated by Django 4.1.9 on 2024-02-27 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0007_remove_inboxmessage_via"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inboxmessage",
            name="hash",
        ),
    ]
