# Generated by Django 4.1.9 on 2024-02-27 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0008_remove_inboxmessage_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inboxmessage",
            name="destination",
        ),
    ]
