# Generated by Django 4.1.9 on 2024-09-27 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0008_alter_profile_identity"),
        ("inbox", "0009_remove_inboxmessage_destination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboxmessage",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_received_messages",
                to="user_profile.profile",
            ),
        ),
    ]
