# Generated by Django 4.1.9 on 2023-10-31 13:58

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_profile", "0001_initial"),
        ("node", "0002_initial"),
        ("terminology", "0001_initial"),
        ("project", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codesystem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_by",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="codesystem",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origin",
                to="node.node",
            ),
        ),
        migrations.AddField(
            model_name="codesystem",
            name="project",
            field=annoying.fields.AutoOneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codesystem",
                to="project.project",
            ),
        ),
        migrations.AddField(
            model_name="codeset",
            name="codes",
            field=models.ManyToManyField(related_name="codesets", to="terminology.code"),
        ),
        migrations.AddField(
            model_name="code",
            name="codesystem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="codes", to="terminology.codesystem"
            ),
        ),
        migrations.AddField(
            model_name="code",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_by",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="code",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origin",
                to="node.node",
            ),
        ),
        migrations.AddConstraint(
            model_name="code",
            constraint=models.UniqueConstraint(
                fields=("codesystem", "code", "created_by"), name="unique_code_per_user"
            ),
        ),
    ]
