# Generated by Django 4.1.9 on 2023-11-28 09:28

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_alter_projectmembership_status"),
        ("terminology", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codesystem",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="codesystem",
            name="project",
            field=annoying.fields.AutoOneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codesystem",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="codesystem",
            name="uri",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
