# Generated by Django 4.1.9 on 2024-04-18 10:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project", "0011_alter_projectmembership_user"),
        ("user_profile", "0006_profile_node"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroundTruthSchema",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("identifier", models.CharField(blank=True, max_length=500, null=True)),
                ("name", models.CharField(max_length=200)),
                ("yaml", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to="user_profile.profile",
                    ),
                ),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="project.project")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroundTruth",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("identifier", models.CharField(blank=True, max_length=500, null=True)),
                ("content", models.TextField(blank=True, default="")),
                ("nr_rows", models.IntegerField(blank=True, default=0)),
                ("nr_columns", models.IntegerField(blank=True, default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to="user_profile.profile",
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ground_truths",
                        to="project_ground_truth.groundtruthschema",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
