# Generated by Django 4.1.9 on 2024-04-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0011_alter_projectmembership_user"),
        ("project_ground_truth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groundtruthschema",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="ground_truth_schemas", to="project.project"
            ),
        ),
    ]
