# Generated by Django 4.1.9 on 2024-04-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_ground_truth", "0002_alter_groundtruthschema_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="groundtruthschema",
            name="is_distributed",
            field=models.BooleanField(default=False),
        ),
    ]
