# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project_case", "0001_initial"),
        ("challenge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Share",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("identifier", models.CharField(blank=True, max_length=500, null=True)),
                ("content", models.JSONField(default=dict)),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(null=True)),
                ("file_query", models.JSONField(default=dict)),
                ("cases", models.ManyToManyField(related_name="shares", to="project_case.case")),
                ("challenges", models.ManyToManyField(related_name="shares", to="challenge.challenge")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
