# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("computing_log", "0001_initial"),
        ("terminology", "0001_initial"),
        ("computing_artifact", "0003_initial"),
        ("share", "0001_initial"),
        ("computing", "0001_initial"),
        ("computing_executions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="codes",
            field=models.ManyToManyField(related_name="shares", to="terminology.code"),
        ),
        migrations.AddField(
            model_name="share",
            name="computing_job_artefacts",
            field=models.ManyToManyField(related_name="shares", to="computing_artifact.computingjobartifact"),
        ),
        migrations.AddField(
            model_name="share",
            name="computing_job_definitions",
            field=models.ManyToManyField(related_name="shares", to="computing.computingjobdefinition"),
        ),
        migrations.AddField(
            model_name="share",
            name="computing_job_executions",
            field=models.ManyToManyField(related_name="shares", to="computing_executions.computingjobexecution"),
        ),
        migrations.AddField(
            model_name="share",
            name="computing_job_logs",
            field=models.ManyToManyField(related_name="shares", to="computing_log.computingjoblogentry"),
        ),
    ]
