# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_profile", "0001_initial"),
        ("challenge_dataset", "0002_initial"),
        ("node", "0002_initial"),
        ("storage", "0002_initial"),
        ("share", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_by",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="datasets",
            field=models.ManyToManyField(related_name="shares", to="challenge_dataset.dataset"),
        ),
        migrations.AddField(
            model_name="share",
            name="files",
            field=models.ManyToManyField(related_name="shares", to="storage.file"),
        ),
        migrations.AddField(
            model_name="share",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origin",
                to="node.node",
            ),
        ),
    ]
