# Generated by Django 4.1.9 on 2023-11-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_projectmembership_status"),
        ("share", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="project",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="share",
            name="file_query",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
