# Generated by Django 4.1.9 on 2023-11-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terminology", "0002_initial"),
        ("share", "0004_share_project_alter_share_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="codesystem",
            field=models.ManyToManyField(related_name="shares", to="terminology.codesystem"),
        ),
    ]
