# Generated by Django 4.1.9 on 2024-01-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extra_data", "0003_initial"),
        ("share", "0005_share_codesystem"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="extra_data",
            field=models.ManyToManyField(related_name="shares", to="extra_data.extradata"),
        ),
    ]
