# Generated by Django 4.1.9 on 2024-04-19 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project_ground_truth", "0002_alter_groundtruthschema_project"),
        ("share", "0007_alter_share_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="ground_truth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shares",
                to="project_ground_truth.groundtruth",
            ),
        ),
    ]
