# Generated by Django 4.1.9 on 2024-04-23 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project_ground_truth", "0002_alter_groundtruthschema_project"),
        ("share", "0009_share_ground_truth_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="share",
            name="ground_truth_schema",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_in_shares",
                to="project_ground_truth.groundtruthschema",
            ),
        ),
    ]
