# Generated by Django 4.1.9 on 2024-04-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenge_submission", "0007_submissiontonodes_submission_nodes"),
        ("share", "0010_alter_share_ground_truth_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="submissions",
            field=models.ManyToManyField(related_name="shares", to="challenge_submission.submission"),
        ),
    ]
