# Generated by Django 4.1.9 on 2024-06-19 11:58

from django.db import migrations, models

from apps.computing.utils import _generate_random_name


def set_migration_names(apps, schema_editor):
    Share = apps.get_model('share', 'Share')
    qs = Share.objects.all()
    for i, s in enumerate(qs):
        s.name = str(i)
        s.save()


class Migration(migrations.Migration):
    dependencies = [
        ("share", "0012_share_evaluation_code"),
    ]

    operations = [
        migrations.RunPython(set_migration_names),
        migrations.AddConstraint(
            model_name="share",
            constraint=models.UniqueConstraint(
                fields=("name", "project", "created_by"), name="unique_share_name_per_project_and_user"
            ),
        ),
    ]
