# Generated by Django 4.1.9 on 2024-10-08 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("share", "0013_share_unique_share_name_per_project_and_user"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="share",
            name="unique_share_name_per_project_and_user",
        ),
    ]
