# Generated by Django 4.1.9 on 2023-10-31 13:58

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("computing_log", "0001_initial"),
        ("challenge_submission", "0001_initial"),
        ("computing", "0001_initial"),
        ("computing_artifact", "0001_initial"),
        ("challenge", "0001_initial"),
        ("computing_executions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionstatus",
            name="executions",
            field=models.ManyToManyField(to="computing_executions.computingjobexecution"),
        ),
        migrations.AddField(
            model_name="submissionstatus",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status",
                to="challenge_submission.submission",
            ),
        ),
        migrations.AddField(
            model_name="submissionlogentry",
            name="log_entry",
            field=annoying.fields.AutoOneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission_log_entry",
                to="computing_log.computingjoblogentry",
            ),
        ),
        migrations.AddField(
            model_name="submissionartefact",
            name="artefact",
            field=annoying.fields.AutoOneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission_artefact",
                to="computing_artifact.computingjobartifact",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="challenge.challenge"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="computing_pipeline",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission",
                to="computing.computingpipeline",
            ),
        ),
    ]
