# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_profile", "0001_initial"),
        ("node", "0001_initial"),
        ("challenge_submission", "0002_initial"),
        ("challenge_targetmetric", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_by",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origin",
                to="node.node",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="submitter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="target_metric_value",
            field=models.ManyToManyField(
                through="challenge_submission.TargetMetricValue", to="challenge_targetmetric.targetmetric"
            ),
        ),
    ]
