# Generated by Django 4.1.9 on 2024-03-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("computing_executions", "0002_initial"),
        ("challenge_submission", "0004_alter_submission_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="computing_job_executions",
            field=models.ManyToManyField(related_name="submissions", to="computing_executions.computingjobexecution"),
        ),
    ]
