# Generated by Django 4.1.9 on 2024-04-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenge_submission", "0005_submission_computing_job_executions"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="reference",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
