# Generated by Django 4.1.9 on 2024-04-15 11:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0006_profile_node"),
        ("challenge_submission", "0006_submission_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionToNodes",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("sent", "Sent"), ("error", "Error"), ("sending", "Sending")],
                        default="pending",
                        max_length=7,
                    ),
                ),
                ("node", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user_profile.profile")),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="challenge_submission.submission"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="submission",
            name="nodes",
            field=models.ManyToManyField(
                blank=True, through="challenge_submission.SubmissionToNodes", to="user_profile.profile"
            ),
        ),
    ]
