# Generated by Django 4.1.9 on 2024-05-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenge_submission", "0007_submissiontonodes_submission_nodes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissiontonodes",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("error", "Error"),
                    ("sending", "Sending"),
                    ("results", "Results"),
                ],
                default="pending",
                max_length=7,
            ),
        ),
    ]
