# Generated by Django 4.1.9 on 2024-05-27 11:29

import django.db.models.deletion
from django.db import migrations, models


def delete_submission_to_nodes(apps, schema_editor):
    SubmissionToNode = apps.get_model("challenge_submission", "SubmissionToNodes")
    SubmissionToNode.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("share_token", "0004_alter_sharetoken_recipient"),
        ("challenge_submission", "0008_alter_submissiontonodes_status"),
    ]

    operations = [
        migrations.RunPython(delete_submission_to_nodes),
        migrations.AddField(
            model_name="submissiontonodes",
            name="share_token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="share_token.sharetoken"
            ),
            preserve_default=False,
        ),
    ]
