# Generated by Django 4.1.9 on 2024-06-18 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("share_token", "0004_alter_sharetoken_recipient"),
        ("challenge_submission", "0009_submissiontonodes_share_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissiontonodes",
            name="share_token",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="share_token.sharetoken"
            ),
        ),
    ]
