# Generated by Django 4.1.9 on 2025-02-24 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("computing_executions", "0002_initial"),
        ("computing", "0004_computingjobdefinition_data_origins"),
        ("challenge_submission", "0010_alter_submissiontonodes_share_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="computing_job_executions",
            field=models.ManyToManyField(
                blank=True, related_name="submissions", to="computing_executions.computingjobexecution"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="computing_pipeline",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission",
                to="computing.computingpipeline",
            ),
        ),
    ]
