# Generated by Django 4.1.9 on 2024-07-29 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_profile", "0006_profile_node"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("actor_identifier", models.CharField(max_length=255)),
                ("actor_display", models.CharField(blank=True, max_length=255, null=True)),
                ("object", models.JSONField(blank=True)),
                ("context", models.JSONField(blank=True)),
                ("action", models.CharField(max_length=255)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="user_profile.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
