# Generated by Django 4.1.9 on 2024-07-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="raw_event",
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="log",
            name="raw_message",
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
    ]
