# Generated by Django 4.1.9 on 2024-07-30 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0006_profile_node"),
        ("blockchain", "0002_log_raw_event_log_raw_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_entries",
                to="user_profile.profile",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="actor_identifier",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
