# Generated by Django 4.1.9 on 2024-07-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0003_alter_log_actor_alter_log_actor_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="context",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
