# Generated by Django 4.1.9 on 2024-07-30 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0004_alter_log_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="event_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
