# Generated by Django 4.1.9 on 2024-10-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0005_log_event_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="event_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="log",
            name="message_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
