# Generated by Django 4.1.9 on 2025-04-01 13:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0006_log_event_id_log_message_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastSeenBlock",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("block", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
