# Generated by Django 4.1.9 on 2025-04-01 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0007_lastseenblock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("number", models.BigIntegerField()),
                ("tx", models.TextField()),
                ("content", models.TextField()),
                ("cid", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
