# Generated by Django 4.1.9 on 2025-04-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0008_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="tx",
            field=models.JSONField(),
        ),
    ]
