# Generated by Django 4.1.9 on 2025-04-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0009_alter_block_tx"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="tx_content",
            field=models.JSONField(default=dict),
        ),
    ]
