# Generated by Django 4.1.9 on 2025-04-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0010_block_tx_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="cid_downloaded",
            field=models.BooleanField(default=False),
        ),
    ]
