# Generated by Django 4.1.9 on 2025-04-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0011_block_cid_downloaded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="content",
            field=models.TextField(default=None, null=True),
        ),
    ]
