# Generated by Django 4.1.9 on 2025-04-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0012_alter_block_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="block_number",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
