# Generated by Django 4.1.9 on 2025-04-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0013_log_block_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="message_hash",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
