# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_profile", "0001_initial"),
        ("share_token", "0001_initial"),
        ("share", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharetoken",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_share_tokens",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="sharetoken",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="share_tokens", to="user_profile.profile"
            ),
        ),
        migrations.AddField(
            model_name="sharetoken",
            name="share",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tokens", to="share.share"
            ),
        ),
    ]
