# Generated by Django 4.1.9 on 2024-02-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0006_profile_node"),
        ("share_token", "0003_alter_sharetoken_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharetoken",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="share_tokens", to="user_profile.profile"
            ),
        ),
    ]
