# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("computing_executions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComputingJobLogEntry",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("identifier", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("output", "Output"), ("error", "Error"), ("info", "Info")],
                        default="output",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(null=True)),
                ("position", models.PositiveIntegerField()),
                ("logged_at", models.DateTimeField()),
                (
                    "computing_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="computing_executions.computingjobexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
