# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileSet",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("identifier", models.CharField(blank=True, max_length=500, null=True)),
                ("name", models.CharField(max_length=100)),
                ("files_count", models.IntegerField(default=0)),
                ("files_imported_count", models.IntegerField(default=0)),
                ("files_total_size", models.BigIntegerField(default=0)),
                ("files_imported_total_size", models.BigIntegerField(default=0)),
                (
                    "annotations",
                    models.ManyToManyField(blank=True, related_name="%(class)s_annotations", to="core.annotation"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
