# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fileset", "0001_initial"),
        ("terminology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileset",
            name="codes",
            field=models.ManyToManyField(blank=True, related_name="%(class)s_codes", to="terminology.code"),
        ),
    ]
