# Generated by Django 4.1.9 on 2024-02-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0006_profile_node"),
        ("fileset", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileset",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origin",
                to="user_profile.profile",
            ),
        ),
    ]
