# Generated by Django 4.1.9 on 2023-10-31 13:58

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project", "0001_initial"),
        ("terminology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="codeset",
            field=annoying.fields.AutoOneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project",
                to="terminology.codeset",
            ),
        ),
    ]
