# Generated by Django 4.1.9 on 2023-11-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmembership",
            name="status",
            field=models.CharField(
                choices=[("invited", "Invited"), ("accepted", "Accepted"), ("declined", "Declined")],
                default="invited",
                max_length=15,
            ),
        ),
    ]
