# Generated by Django 4.1.9 on 2023-11-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_projectmembership_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("invited", "Invited"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("owner", "Owner"),
                ],
                default="invited",
                max_length=15,
            ),
        ),
    ]
