# Generated by Django 4.1.9 on 2024-02-27 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0005_profile_organization"),
        ("project", "0005_alter_projectmembership_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="projectmembership",
            name="unique_node_in_project",
        ),
        migrations.RemoveField(
            model_name="projectmembership",
            name="node",
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="projects",
                to="user_profile.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="projectmembership",
            constraint=models.UniqueConstraint(fields=("project", "user"), name="unique_user_in_project"),
        ),
    ]
