# Generated by Django 4.1.9 on 2024-02-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("federation_invitation", "0006_federationinvitation_project_data"),
        ("project", "0007_alter_project_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmembership",
            name="invite",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_membership",
                to="federation_invitation.federationinvitation",
            ),
        ),
    ]
