# Generated by Django 4.1.9 on 2024-02-28 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0008_projectmembership_invite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmembership",
            name="status",
        ),
    ]
