# Generated by Django 4.1.9 on 2024-03-01 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0006_profile_node"),
        ("project", "0010_alter_projectmembership_invite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="projects", to="user_profile.profile"
            ),
        ),
    ]
