# Generated by Django 4.1.9 on 2024-10-07 13:03

import uuid

import django.db.models.deletion
from django.db import migrations, models
#
# def forwards_func(apps, schema_editor):
#     Project = apps.get_model('project', 'Project')
#     FilePermission = apps.get_model('project', 'FilePermission')
#     Profile = apps.get_model('user_profile', 'Profile')
#
#     for p in Project.objects.all():
#         for f in p.files.through.objects.all():
#             created_by = p.created_by if p.created_by is not None else Profile.objects.get(user__username='node')
#             FilePermission.objects.create(
#                 project=p,
#                 file=f.file,
#                 user=created_by
#             )


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0011_alter_profile_communication_allowed_with_users"),
        ("storage", "0006_alter_file_import_folder_alter_file_path"),
        ("project", "0011_alter_projectmembership_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilePermission",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="project", to="storage.file"
                    ),
                ),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="project.project")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="files", to="user_profile.profile"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(model_name="project", name="files"),
        migrations.AddField(
            model_name="project",
            name="files",
            field=models.ManyToManyField(
                blank=True, related_name="projects", through="project.FilePermission", to="storage.file"
            ),
        ),
    ]
