# Generated by Django 4.1.9 on 2024-10-07 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0006_alter_file_import_folder_alter_file_path"),
        ("user_profile", "0011_alter_profile_communication_allowed_with_users"),
        ("project", "0012_filepermission_alter_project_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="filepermission",
            name="imported",
            field=models.BooleanField(default=False),
        ),
        # migrations.AlterField(
        #     model_name="filepermission",
        #     name="file",
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="storage.file"),
        # ),
        # migrations.AlterField(
        #     model_name="filepermission",
        #     name="user",
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user_profile.profile"),
        # ),
        # migrations.AlterField(
        #     model_name="project",
        #     name="files",
        #     field=models.ManyToManyField(blank=True, related_name="projects", to="storage.file"),
        # ),
    ]
