# Generated by Django 4.1.9 on 2024-10-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0006_alter_file_import_folder_alter_file_path"),
        ("user_profile", "0011_alter_profile_communication_allowed_with_users"),
        ("project", "0013_filepermission_imported_alter_filepermission_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filepermission",
            name="file",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="storage.file"),
        ),
        migrations.AlterField(
            model_name="filepermission",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user_profile.profile"),
        ),
        # migrations.AlterField(
        #     model_name="project",
        #     name="files",
        #     field=models.ManyToManyField(blank=True, related_name="projects", to="storage.file"),
        # ),
    ]
