# Generated by Django 4.1.9 on 2024-10-07 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0014_alter_filepermission_file_alter_filepermission_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="files",
        ),
    ]
