# Generated by Django 4.1.9 on 2024-10-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0006_alter_file_import_folder_alter_file_path"),
        ("project", "0016_remove_project_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="files",
            field=models.ManyToManyField(blank=True, related_name="projects", to="storage.file"),
        ),
    ]
