# Generated by Django 4.1.9 on 2024-10-08 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0017_project_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="files",
        ),
    ]
