# Generated by Django 4.1.9 on 2024-10-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0019_project_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataview",
            name="datatable_config",
            field=models.TextField(blank=True, default=""),
        ),
    ]
