# Generated by Django 4.1.9 on 2024-10-17 10:56
import json

from django.db import migrations



def populate_status(apps, schema_editor):
    DataView = apps.get_model('project', 'DataView')

    for instance in DataView.objects.all():
        try:
            s = json.loads(instance.datatable_config)
            instance.datatable_config = s['columns']
            instance.save()
        except Exception as e:
            print(e)

class Migration(migrations.Migration):
    dependencies = [
        ("project", "0020_alter_dataview_datatable_config"),
    ]

    operations = [
        migrations.RunPython(populate_status),
    ]
