# Generated by Django 4.1.9 on 2024-10-17 11:07

from django.db import migrations
def populate_status(apps, schema_editor):
    DataView = apps.get_model('project', 'DataView')

    for instance in DataView.objects.all():
        try:
            instance.datatable_config = """[{
          "data": "name",
          "title": "Name",
          render: (data, type, row, meta) => {
            console.log(row)
            if (row.imported) {
              return `<strong><a href="${row.href}">${data}</a></strong>`
            }
            return data;
          }
         },
          {
            "data": "date_created",
            "title": "Created at",
            render: DataTable.render.datetime()
          },
          {
            "data": "origin.human_readable",
            name: 'origin__human_readable',
            "title": "Origin"
          },
          {
            data: 'case',
            title: 'Case'
          },
          {data: 'terms', title: 'Terms'},
          {data: 'studies', title: 'Local Cohort'}
        ]"""
            instance.save()
        except Exception as e:
            print(e)

class Migration(migrations.Migration):
    dependencies = [
        ("project", "0021_modify_project_data_table_config"),
    ]

    operations = [
        migrations.RunPython(populate_status),
    ]
