# Generated by Django 4.1.9 on 2024-10-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0022_dataview_create_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataview",
            name="js",
            field=models.TextField(blank=True, default=""),
        ),
    ]
