# Generated by Django 4.1.9 on 2025-02-25 15:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0011_alter_profile_communication_allowed_with_users"),
        ("extra_data", "0006_remove_extradata__extradata_idx_file"),
        ("project", "0023_dataview_js"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectExtraData",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("imported", models.BooleanField(default=False)),
                (
                    "extra_data",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="extra_data.extradata"),
                ),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="project.project")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user_profile.profile")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="project",
            name="extra_data",
            field=models.ManyToManyField(
                blank=True, related_name="projects", through="project.ProjectExtraData", to="extra_data.extradata"
            ),
        ),
    ]
