# Generated by Django 4.1.9 on 2025-11-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terminology", "0004_alter_code_origin_alter_codesystem_origin"),
        ("project", "0024_projectextradata_project_extra_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="biomarkers",
            field=models.ManyToManyField(blank=True, related_name="project_biomarkers", to="terminology.code"),
        ),
        migrations.AddField(
            model_name="project",
            name="disease",
            field=models.ManyToManyField(blank=True, related_name="project_disease", to="terminology.code"),
        ),
        migrations.AddField(
            model_name="project",
            name="intended_use",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="population",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="tissue",
            field=models.ManyToManyField(blank=True, related_name="project_tissue", to="terminology.code"),
        ),
    ]
