# Generated by Django 4.1.9 on 2024-02-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="google_scholar",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="orcid",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="pubmed",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name="ProfileAuthentication",
        ),
    ]
