# Generated by Django 4.1.9 on 2024-02-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0003_profile_google_scholar_profile_orcid_profile_pubmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="registry_id",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
