# Generated by Django 4.1.9 on 2024-02-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0004_profile_registry_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="organization",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
