# Generated by Django 4.1.9 on 2024-02-27 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0004_node_common_name"),
        ("user_profile", "0005_profile_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="node",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="users", to="node.node"
            ),
        ),
    ]
