# Generated by Django 4.1.9 on 2024-09-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0006_profile_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="identity",
            field=models.CharField(default="did", max_length=100),
            preserve_default=False,
        ),
    ]
