# Generated by Django 4.1.9 on 2024-09-25 09:13

from django.db import migrations, models

def update_field(apps, schema_editor):
    Profile = apps.get_model('user_profile', 'Profile')
    # Update the field for all instances of YourModel

    for p in Profile.objects.all():
        p.identity = f'did:{p.id}'
        p.save(update_fields=['identity'])
    # YourModel.objects.filter(your_field__isnull=True).update(your_field='new_value')


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0007_profile_identity"),
    ]

    operations = [
        migrations.RunPython(update_field),
        migrations.AlterField(
            model_name="profile",
            name="identity",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
