# Generated by Django 4.1.9 on 2024-09-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0008_alter_profile_identity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="registry_id",
        ),
        migrations.AddField(
            model_name="profile",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
