# Generated by Django 4.1.9 on 2024-09-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0009_remove_profile_registry_id_profile_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="communication_allowed_with_users",
            field=models.ManyToManyField(to="user_profile.profile"),
        ),
    ]
