# Generated by Django 4.1.9 on 2024-09-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0010_profile_communication_allowed_with_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="communication_allowed_with_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="The list of users allowed to send a message to this particular user.",
                to="user_profile.profile",
            ),
        ),
    ]
