# Generated by Django 4.1.9 on 2025-04-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0011_alter_profile_communication_allowed_with_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="private_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
