# Generated by Django 4.1.9 on 2025-04-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0012_profile_private_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="eth_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
