# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("challenge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetMetric",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("identifier", models.CharField(blank=True, max_length=500, null=True)),
                ("sort", models.CharField(choices=[("asc", "Asc"), ("desc", "Desc")], max_length=4, null=True)),
                ("key", models.CharField(max_length=200)),
                (
                    "dtype",
                    models.CharField(
                        choices=[("int", "Int"), ("float", "Float"), ("string", "Str")], default="float", max_length=6
                    ),
                ),
                ("filename", models.CharField(max_length=100)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_metrics",
                        to="challenge.challenge",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
