# Generated by Django 4.1.9 on 2025-11-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenge_targetmetric", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetmetric",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="targetmetric",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
