# Generated by Django 4.1.9 on 2023-10-31 13:58

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("identifier", models.CharField(blank=True, max_length=500, null=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "annotations",
                    models.ManyToManyField(blank=True, related_name="%(class)s_annotations", to="core.annotation"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseDescription",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("description", models.TextField()),
                (
                    "case",
                    annoying.fields.AutoOneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="description", to="project_case.case"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
