# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_profile", "0001_initial"),
        ("node", "0002_initial"),
        ("project_case", "0002_initial"),
        ("project", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_by",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origin",
                to="node.node",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="projects",
            field=models.ManyToManyField(blank=True, related_name="cases", to="project.project"),
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.UniqueConstraint(
                fields=("identifier", "created_by", "origin"), name="unique_case_per_user"
            ),
        ),
    ]
