# Generated by Django 4.1.9 on 2023-11-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outbox", "0003_outboxmessage_extra_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxmessage",
            name="response_body",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
