# Generated by Django 4.1.9 on 2024-02-27 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("outbox", "0005_alter_outboxmessage_recipient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outboxmessage",
            name="via",
        ),
    ]
