# Generated by Django 4.1.9 on 2024-02-27 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("outbox", "0006_remove_outboxmessage_via"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outboxmessage",
            name="hash",
        ),
    ]
