# Generated by Django 4.1.9 on 2024-02-27 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("outbox", "0007_remove_outboxmessage_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outboxmessage",
            name="destination",
        ),
    ]
