# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("identifier", models.CharField(blank=True, max_length=500, null=True)),
                ("name", models.CharField(max_length=100)),
                ("open_from", models.DateTimeField()),
                ("open_until", models.DateTimeField()),
                ("dataset_name", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=200)),
                ("pipeline_yml", models.TextField(blank=True, null=True)),
                (
                    "annotations",
                    models.ManyToManyField(blank=True, related_name="%(class)s_annotations", to="core.annotation"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
