# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("node", "0001_initial"),
        ("project", "0002_initial"),
        ("user_profile", "0001_initial"),
        ("challenge", "0002_initial"),
        ("computing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_by",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origin",
                to="node.node",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="pipeline",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="computing.computingpipeline"
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="project",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="challenges", to="project.project"
            ),
        ),
    ]
