# Generated by Django 4.1.9 on 2023-11-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0004_remove_challenge_dataset_name_alter_challenge_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
