# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("study_management", "0001_initial"),
        ("project", "0001_initial"),
        ("storage_importer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="study",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="study_management.study"
            ),
        ),
        migrations.AddField(
            model_name="importfolder",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_folders",
                to="project.project",
            ),
        ),
        migrations.AddField(
            model_name="importfolder",
            name="study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_folders",
                to="study_management.study",
            ),
        ),
        migrations.AddField(
            model_name="importfolder",
            name="study_arm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_folders",
                to="study_management.studyarm",
            ),
        ),
    ]
