# Generated by Django 4.1.9 on 2023-11-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="node",
            old_name="address",
            new_name="address_centauron",
        ),
        migrations.AddField(
            model_name="node",
            name="address_fhir_server",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
    ]
