# Generated by Django 4.1.9 on 2023-11-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0003_rename_address_node_address_centauron_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="common_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
