# Generated by Django 4.1.9 on 2024-03-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0004_node_common_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="cdn_address",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
    ]
