# Generated by Django 4.1.9 on 2024-09-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0005_node_cdn_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="address_fhir_server",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
