# Generated by Django 4.1.9 on 2024-09-27 14:03

from django.db import migrations, models


def set_did(apps, schema_editor):
    # Get your model
    Node = apps.get_model('node', 'Node')

    for n in Node.objects.all():
        n.did = f'did:{n.pk}'
        n.save()

class Migration(migrations.Migration):
    dependencies = [
        ("node", "0006_alter_node_address_fhir_server"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="did",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(set_did)
    ]
