# Generated by Django 4.1.9 on 2024-09-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0007_node_did"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="did",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
