# Generated by Django 4.1.9 on 2024-12-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0008_alter_node_did"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="api_address",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
