# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project_case", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("identifier", models.CharField(blank=True, max_length=500, null=True)),
                ("name", models.CharField(max_length=1000)),
                ("content_type", models.CharField(blank=True, default=None, max_length=100, null=True)),
                ("imported", models.BooleanField(default=False)),
                ("original_filename", models.CharField(max_length=1000)),
                ("original_path", models.CharField(max_length=1000)),
                ("path", models.CharField(default=None, max_length=1000, null=True)),
                ("size", models.BigIntegerField(default=-1)),
                (
                    "annotations",
                    models.ManyToManyField(blank=True, related_name="%(class)s_annotations", to="core.annotation"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="project_case.case",
                    ),
                ),
            ],
        ),
    ]
