# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_profile", "0001_initial"),
        ("node", "0002_initial"),
        ("storage", "0002_initial"),
        ("storage_importer", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_by",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="import_folder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="storage_importer.importfolder",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origin",
                to="node.node",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="originating_from",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="children_files",
                to="storage.file",
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["identifier"], name="storage_fil_identif_cd3e82_idx"),
        ),
    ]
