# Generated by Django 4.1.9 on 2024-04-18 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0004_alter_file_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="originating_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="children_files",
                to="storage.file",
            ),
        ),
    ]
