# Generated by Django 4.1.9 on 2024-05-14 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("storage_importer", "0002_initial"),
        ("storage", "0005_alter_file_originating_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="import_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="storage_importer.importfolder",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="path",
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
