# Generated by Django 4.1.9 on 2025-11-10 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0025_project_biomarkers_project_disease_and_more"),
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectwebsite",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="website", to="project.project"
            ),
        ),
    ]
