# Generated by Django 4.1.9 on 2025-11-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_alter_projectwebsite_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectwebsite",
            name="hero",
            field=models.TextField(blank=True, null=True),
        ),
    ]
