# Generated by Django 4.1.9 on 2025-11-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_projectwebsite_hero"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectwebsite",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
