# Generated by Django 4.1.9 on 2025-11-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_projectwebsite_contact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectwebsite",
            name="affiliation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
