# Generated by Django 4.1.9 on 2023-10-31 13:58

import apps.computing.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComputingJobDefinition",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("identifier", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "execution_type",
                    models.CharField(choices=[("manual", "Manual"), ("auto", "Auto")], default="auto", max_length=6),
                ),
                ("namespace", models.CharField(blank=True, max_length=63)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("docker_image", models.CharField(blank=True, max_length=500, null=True)),
                ("result", models.JSONField(blank=True, default=dict, null=True)),
                ("k8s_spec", models.JSONField(blank=True, default=None, null=True)),
                ("output", models.JSONField(blank=True, default=list)),
                ("input", models.JSONField(blank=True, default=list)),
                (
                    "type",
                    models.CharField(
                        choices=[("training", "Training"), ("validation", "Validation")],
                        default="training",
                        max_length=20,
                    ),
                ),
                ("entrypoint", models.JSONField(blank=True, default=None, null=True)),
                ("retagged_docker_image", models.CharField(blank=True, default=None, max_length=500, null=True)),
                ("credentials", models.JSONField(blank=True, default=None, null=True)),
                ("position", models.IntegerField(default=1)),
                ("resources", models.JSONField(blank=True, default=None, null=True)),
                ("data_file", models.CharField(blank=True, max_length=500, null=True)),
                ("batch_size", models.IntegerField(blank=True, default=-1)),
                ("total_batches", models.IntegerField(blank=True, default=-1)),
                ("environment_variables", models.JSONField(blank=True, default=dict, null=True)),
                ("environment_variables_job_context", models.JSONField(blank=True, default=dict, null=True)),
                ("args", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ComputingJobTemplate",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("identifier", models.CharField(blank=True, max_length=500, null=True)),
                ("template_fields", models.JSONField(blank=True, default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ComputingPipeline",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("identifier", models.CharField(blank=True, max_length=500, null=True)),
                ("name", models.CharField(default=apps.computing.utils._generate_random_name, max_length=200)),
                ("error", models.TextField(blank=True, default=None, null=True)),
                ("is_template", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
