# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("node", "0001_initial"),
        ("user_profile", "0001_initial"),
        ("computing", "0001_initial"),
        ("challenge_dataset", "0002_initial"),
        ("challenge_submission", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="computingpipeline",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_by",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="computingpipeline",
            name="instantiated_from",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="computing.computingpipeline"
            ),
        ),
        migrations.AddField(
            model_name="computingpipeline",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origin",
                to="node.node",
            ),
        ),
        migrations.AddField(
            model_name="computingjobtemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_by",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="computingjobtemplate",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origin",
                to="node.node",
            ),
        ),
        migrations.AddField(
            model_name="computingjobdefinition",
            name="copied_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="computing.computingjobdefinition",
            ),
        ),
        migrations.AddField(
            model_name="computingjobdefinition",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_by",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="computingjobdefinition",
            name="dataset",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="challenge_dataset.dataset"
            ),
        ),
        migrations.AddField(
            model_name="computingjobdefinition",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origin",
                to="node.node",
            ),
        ),
        migrations.AddField(
            model_name="computingjobdefinition",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="computing.computingpipeline",
            ),
        ),
        migrations.AddField(
            model_name="computingjobdefinition",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="challenge_submission.submission",
            ),
        ),
        migrations.AddField(
            model_name="computingjobdefinition",
            name="template",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="definition",
                to="computing.computingjobtemplate",
            ),
        ),
    ]
