# Generated by Django 4.1.9 on 2024-04-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0006_profile_node"),
        ("computing", "0003_alter_computingjobdefinition_origin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="computingjobdefinition",
            name="data_origins",
            field=models.ManyToManyField(blank=True, to="user_profile.profile"),
        ),
    ]
