# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_profile", "0001_initial"),
        ("challenge_client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengeparticipants",
            name="profiles",
            field=models.ManyToManyField(related_name="participating_in", to="user_profile.profile"),
        ),
    ]
