# Generated by Django 4.1.9 on 2025-03-07 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0011_alter_profile_communication_allowed_with_users"),
        ("challenge_client", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeParticipantApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("approved", models.BooleanField(default=False)),
                (
                    "challenge_participants",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_approvals",
                        to="challenge_client.challengeparticipants",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_approvals",
                        to="user_profile.profile",
                    ),
                ),
            ],
            options={
                "unique_together": {("challenge_participants", "profile")},
            },
        ),
        migrations.AddField(
            model_name="challengeparticipants",
            name="profiles2",
            field=models.ManyToManyField(
                related_name="participating_in2",
                through="challenge_client.ChallengeParticipantApproval",
                to="user_profile.profile",
            ),
        ),
    ]
