# Generated by Django 4.1.9 on 2025-03-07 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("challenge_client", "0003_challengeparticipantapproval_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challengeparticipants",
            name="profiles",
        ),
    ]
