# Generated by Django 4.1.9 on 2025-03-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0011_alter_profile_communication_allowed_with_users"),
        ("challenge_client", "0004_remove_challengeparticipants_profiles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challengeparticipants",
            name="profiles2",
        ),
        migrations.AddField(
            model_name="challengeparticipants",
            name="profiles",
            field=models.ManyToManyField(
                related_name="participating_in",
                through="challenge_client.ChallengeParticipantApproval",
                to="user_profile.profile",
            ),
        ),
    ]
