# Generated by Django 4.1.9 on 2025-03-07 10:46

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("challenge_client", "0005_remove_challengeparticipants_profiles2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengeparticipantapproval",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="challengeparticipantapproval",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunSQL(
            'alter table challenge_client_challengeparticipantapproval drop column id;'
        ),
        migrations.AddField(
            model_name="challengeparticipantapproval",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
