# Generated by Django 4.1.9 on 2023-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_profile", "0001_initial"),
        ("permission", "0001_initial"),
        ("user_group", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_by",
                to="user_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="group",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permissions",
                to="user_group.group",
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="permissions", to="user_profile.profile"
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["object_identifier"], name="permission__object__dd76c0_idx"),
        ),
        migrations.AddConstraint(
            model_name="permission",
            constraint=models.UniqueConstraint(
                fields=("action", "permission", "user_id", "object_identifier"), name="unique_permission"
            ),
        ),
    ]
