# Generated by Django 4.1.9 on 2024-02-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0006_profile_node"),
        ("permission", "0003_alter_permission_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="permissions", to="user_profile.profile"
            ),
        ),
    ]
